### ISSUE TITLE
yarn build demo

### ISSUE THREAD

**Issue by mingtianshi** [react-native-voice/voice#370]
~~~
yarn run v1.22.17
info Commands available from binary scripts: JSONStream, acorn, atob, babylon, cdl, color-support, conventional-changelog-writer, conventional-commits-parser, detect-libc, envinfo, errno, eslint, eslint-config-prettier-check, esparse, esvalidate, handlebars, image-size, is-ci, js-yaml, jsesc, json5, lint-staged, lock-verify, loose-envify, marked, metro, mime, mkdirp, needle, node-gyp, node-pre-gyp, node-which, nopt, npm, npm-path, npm-which, npx, opener, parser, pegjs, prettier, qrcode-terminal, rc, react-native, regjsparser, rimraf, sane, semantic-release, semver, sgf, sshpk-conv, sshpk-sign, sshpk-verify, tsc, tsserver, uglifyjs, uuid, watch
info Project commands
   - android
      yarn --cwd example android
   - build
      tsc
   - build:plugin
      tsc --build plugin
   - dev-sync
      cp -r ./dist example/node_modules/@react-native-voice/voice
   - ios
      yarn --cwd example ios
   - lint
      eslint src/*
   - lint:plugin
      eslint plugin/src/*
   - prepare
      yarn build && yarn build:plugin
   - semantic-release
      semantic-release
   - start
      yarn --cwd example start
   - type-check
      tsc -noEmit
question Which command would you like to run?: android
$ yarn --cwd example android
$ react-native run-android
/Volumes/application/voice/voice/node_modules/@babel/core/lib/config/files/plugins.js:151
    throw e;
    ^

Error: Cannot find module 'metro-react-native-babel-preset' from '/Volumes/application/voice/voice/example'
    at Function.module.exports [as sync] (/Volumes/application/voice/voice/node_modules/@babel/core/node_modules/resolve/lib/sync.js:43:15)
    at resolveStandardizedName (/Volumes/application/voice/voice/node_modules/@babel/core/lib/config/files/plugins.js:100:31)
    at resolvePreset (/Volumes/application/voice/voice/node_modules/@babel/core/lib/config/files/plugins.js:57:10)
    at loadPreset (/Volumes/application/voice/voice/node_modules/@babel/core/lib/config/files/plugins.js:76:20)
    at createDescriptor (/Volumes/application/voice/voice/node_modules/@babel/core/lib/config/config-descriptors.js:135:21)
    at /Volumes/application/voice/voice/node_modules/@babel/core/lib/config/config-descriptors.js:87:50
    at Array.map (<anonymous>)
    at createDescriptors (/Volumes/application/voice/voice/node_modules/@babel/core/lib/config/config-descriptors.js:87:29)
    at createPresetDescriptors (/Volumes/application/voice/voice/node_modules/@babel/core/lib/config/config-descriptors.js:79:10)
    at /Volumes/application/voice/voice/node_modules/@babel/core/lib/config/config-descriptors.js:61:19 {
  code: 'MODULE_NOT_FOUND'
}

Node.js v17.2.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~~~
This problem arose when using this project

**Comment by safaiyeh** [comment]
This project has been deprecated and archived. Please migrate to [`expo-speech-recognition`](https://github.com/jamsch/expo-speech-recognition). Thank you for your contributions! ❤️

**Comment by safaiyeh** [comment]
This project has been deprecated and archived. Please migrate to [`expo-speech-recognition`](https://github.com/jamsch/expo-speech-recognition).
Thank you for your contributions! ❤️
