### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference [ANDROID]

### ISSUE THREAD

**Issue by mehdinourollah** [react-native-voice/voice#384]
When I use it on Android the app crashes and I've got this error from logcat

```2022-04-29 17:22:39.664 18659-18659/com.****** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.******, PID: 18659
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
        at com.wenkesj.voice.VoiceModule.onResults(VoiceModule.java:348)
        at android.speech.SpeechRecognizer$InternalListener$1.handleMessage(SpeechRecognizer.java:459)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by mehdinourollah** [comment]
It's happening the moment that it tries to recognize the voice.

**Comment by mehdinourollah** [comment]
The VoiceModule.java the mentioned part is this part :
```@Override
  public void onResults(Bundle results) {
    WritableArray arr = Arguments.createArray();

    ArrayList<String> matches = results.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);
    for (String result : matches) {
      arr.pushString(result);
    }
    ...

**Comment by Thanhal-P-A** [comment]
In my case, this solution works : [[@react-native-community/voice or react-native-voice / voice gives exception java.lang.NullPointerException at com.wenkesj.voice.VoiceModule.onResults](https://stackoverflow.com/questions/72213425/react-native-community-voice-or-react-native-voice-voice-gives-exception-java)](https://stackoverflow.com/questions/72213425/react-native-community-voice-or-react-native-voice-voice-gives-exception-java/72213426#72213426)

**Comment by mehdinourollah** [comment]
As far as I checked it's not a solution ...It just removed some parameters from Start function ( which I can't )

> In my case, this solution works : [[@react-native-community/voice or react-native-voice / voice gives exception java.lang.NullPointerException at com.wenkesj.voice.VoiceModule.onResults](https://stackoverflow.com/questions/72213425/react-native-community-voice-or-react-native-voice-voice-gives-exception-java)](https://stackoverflow.com/questions/72213425/react-native-community-voice-or-react-native-voice-voice-gives-exception-java/72213426#72213426)

**Comment by Nikit-Singh** [comment]
@mehdinourollah did you find any solution for this without removing the parameters?

**Comment by mehdinourollah** [comment]
No I couldn't Unfortunately

**Comment by Alaaeddine-chakroun** [comment]
I managed to fix the crash on android by removing ```EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS``` from the options in Voice.start

**Comment by goheroes** [comment]
#435 
I need your usage tests and feedback.

**Comment by brian-pinwheel** [comment]
The PR above was merged and should resolve the issue.  Unfortunately, there hasn't been a release in over 2 years so there is not a good way to pick up this fix.

Thanks @goheroes for resolving the issue!

**Comment by safaiyeh** [comment]
This project has been deprecated and archived. Please migrate to [`expo-speech-recognition`](https://github.com/jamsch/expo-speech-recognition). Thank you for your contributions! ❤️
